repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.21
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: terragrunt-hclfmt
      - id: tflint
      - id: shellcheck
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
