# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-934492087370"
    dynamodb_table = "terraform-lock-table"
    encrypt        = true
    key            = "modules/credentials/terraform.tfstate"
    kms_key_id     = "arn:aws:kms:us-east-1:934492087370:alias/terraform-state-934492087370"
    profile        = "AWSAdministratorAccess-934492087370"
    region         = "us-east-1"
  }
}
